USE McDev;
GO
ALTER TABLE Employee WITH CHECK
ADD CONSTRAINT FK_JobID FOREIGN KEY(JobID) REFERENCES Positions(JobID)
ON UPDATE CASCADE
GO
ALTER TABLE Branch WITH CHECK
ADD CONSTRAINT FK_ZipCode FOREIGN KEY(ZipCode) REFERENCES ZipCode(ZipCode)
ON UPDATE CASCADE
GO
ALTER TABLE Projects WITH CHECK
ADD CONSTRAINT FK_BranchID FOREIGN KEY(BranchID) REFERENCES Branch(BranchID)
ON UPDATE CASCADE
GO
ALTER TABLE EmployeeProjects WITH CHECK
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY(EmployeeID) REFERENCES Employee(EmployeeID)
ON UPDATE CASCADE
GO
ALTER TABLE EmployeeProjects WITH CHECK
ADD CONSTRAINT FK_ProjectID FOREIGN KEY(ProjectID) REFERENCES Projects(ProjectID)
ON UPDATE CASCADE
GO